embedded_components {
  id: "tile"
  type: "sprite"
  data: "default_animation: \"1\"\n"
  "material: \"/gpu/tile.material\"\n"
  "offset: 0.24\n"
  "playback_rate: 0.0\n"
  "attributes {\n"
  "  name: \"col0\"\n"
  "  double_values {\n"
  "    v: 0.0\n"
  "    v: 0.0\n"
  "    v: 1.0\n"
  "    v: 1.0\n"
  "  }\n"
  "}\n"
  "attributes {\n"
  "  name: \"col1\"\n"
  "  double_values {\n"
  "    v: 1.0\n"
  "    v: 1.0\n"
  "    v: 0.0\n"
  "    v: 1.0\n"
  "  }\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/gpu/jpetscii.tilesource\"\n"
  "}\n"
  ""
  position {
    x: 4.0
    y: 4.0
  }
}
