local debugger = require('boot.debugger')
debugger.start()

local Screen = require('protoedge.screen')
local new_Layer = require('protoedge.layer')

local layer = new_Layer()

function init(self)
	msg.post("@render:", "set_size", { width = Screen.WIDTH, height = Screen.HEIGHT })
	msg.post("@render:", "set_scale_snap", { snap = true })
end

function update(self, dt)
	for x = 1, Screen.COLS do
		for y = 1, Screen.ROWS do
			layer:poke(x, y, math.random(1, 155), math.random(1, 31), math.random(1, 31))
		end
	end
	layer:update()
end
