-- 1) Set up debugger
local debugger = require('boot.debugger')
debugger.start()

-- 2) Initialize the engine itself (only what is required for tests)
local Screen = require('protoedge.screen')
function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "set_size", { width = Screen.WIDTH, height = Screen.HEIGHT })
	msg.post("@render:", "set_scale_snap", { snap = true })
end

-- 3) Update loop kicks off remaining initialization steps in sequence
local LayerBoss = require('protoedge.layer_boss')
local YarnBoss = require('protoedge.yarn_boss')
local TheTests = require('test.the_tests')
local the_game = require('protoedge.game')

local test_phase = true
local game_phase = false

function fixed_update(self) -- 60 FPS
	-- FUTURE: strongly consider a work-item queue to manage "boot sequence" as it gets more complex (and sequencing for other long-running async operations)
	-- 4) Run (or resume) unit tests - running live in engine
	if test_phase then
		local is_done = TheTests.run_or_resume()
		if is_done then
			test_phase = false
			if TheTests.test_status ~= 'success' then
				-- TODO: display test details in console
				error(TheTests.test_summary or string.format('Test result: %s', TheTests.test_status))
			end
		end
	else
		-- 5) Boot up game itself
		if not game_phase then
			local success, err = pcall(the_game)
			game_phase = true -- don't repeat failed bootup
			if not success then
				error('-- TODO: error booting game')
			end
		end
	end

	-- 4+5) The core Z3UX engine loop
	YarnBoss.tick()
	LayerBoss.update()
end

-- Handle other Defold incoming APIs e.g. input
local InputBoss = require('input.input_boss')

---@param action_id hash
---@param action on_input.action
function on_input(self, action_id, action)
	InputBoss.on_input(action_id, action)
end
